version: '3.3'

services:

  wordpress:
    build: ./
    container_name: spa-wellness-japan
    ports:
      - "8000:80"
    restart: "no"
    volumes:
      - ./:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./wp-install:/tmp/wp-install/
    working_dir: /var/www/html/wp
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: mysql_password
      WORDPRESS_DB_NAME: wordpress_db
    depends_on:
      - db

  db:
    image: mysql:8.4.3
    volumes:
      - ./db_data:/var/lib/mysql
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: mysql_password

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: "no"
    environment:
      PMA_HOST: db

volumes:
  db_data: {}
